# Generated by Django 5.2.5 on 2025-09-02 18:10

import datetime
import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_recruteur_entreprise_recruteur_numero_telephone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive_Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent_id', models.IntegerField(blank=True, null=True)),
                ('forum_id', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=150)),
                ('cv', models.FileField(default='', upload_to='archive/cv_candidats')),
                ('numero_telephone', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='archive/image_candidature')),
                ('presence', models.BooleanField(default=False)),
                ('event_horaire', models.CharField(blank=True, max_length=255, null=True)),
                ('date_inscri', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('annotation_candidat', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='archive_forum',
            name='forum',
        ),
        migrations.AddField(
            model_name='archive_forum',
            name='currentNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archive_forum',
            name='date_debut',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='archive_forum',
            name='date_fin',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='archive_forum',
            name='date_forum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archive_forum',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='archive_forum',
            name='duree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive_forum',
            name='entreprise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archive_forum',
            name='lieu',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='archive_forum',
            name='nom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='archive_forum',
            name='nombre_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archive_forum',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='codes_QR'),
        ),
        migrations.AddField(
            model_name='archive_forum',
            name='recruteurs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='candidature_forum',
            name='date_inscri',
            field=models.DateField(default=datetime.date(2025, 9, 2), max_length=100),
        ),
        migrations.DeleteModel(
            name='Archive_talent',
        ),
    ]
