# Generated by Django 5.2.5 on 2025-09-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_archive_candidat_remove_archive_forum_forum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='universite',
        ),
        migrations.DeleteModel(
            name='Universite',
        ),
    ]
