# Generated by Django 5.2.5 on 2025-09-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_archive_candidat_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive_candidat',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='archive_candidat',
            name='etat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archive_candidat',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='archive_candidat',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='archive_candidat',
            name='note',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archive_candidat',
            name='numero_telephone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='archive_forum',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='archive_forum',
            name='lieu',
            field=models.CharField(default='', max_length=100),
        ),
    ]
