# Generated by Django 5.2.5 on 2025-09-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_archive_candidat_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive_forum',
            name='entreprise',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
