# Generated by Django 5.2.5 on 2025-09-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_archive_forum_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive_candidat',
            name='etat',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
