# Generated by Django 5.2.5 on 2025-09-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_archive_candidat_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive_candidat',
            name='etat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
