# Generated by Django 5.2.5 on 2025-09-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_archive_candidat_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive_candidat',
            name='cv',
            field=models.FileField(default='', max_length=255, upload_to='archive/cv_candidats'),
        ),
        migrations.AlterField(
            model_name='archive_candidat',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='archive/image_candidature'),
        ),
    ]
