# Generated by Django 5.2.5 on 2025-09-03 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_archive_candidat_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive_forum',
            name='forum_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidature_forum',
            name='date_inscri',
            field=models.DateField(default=datetime.date(2025, 9, 3), max_length=100),
        ),
    ]
