# Generated by Django 5.2.5 on 2025-09-08 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_archive_forum_forum_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature_forum',
            name='date_inscri',
            field=models.DateField(default=datetime.date(2025, 9, 8), max_length=100),
        ),
        migrations.DeleteModel(
            name='Entretien',
        ),
    ]
