# Generated by Django 5.2.5 on 2026-05-29 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_candidature_forum_date_inscri_delete_entretien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature_forum',
            name='date_inscri',
            field=models.DateField(default=datetime.date(2026, 5, 30), max_length=100),
        ),
    ]
