# Generated by Django 5.2.5 on 2026-06-18 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_candidature_forum_date_inscri'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('reset_token', models.CharField(blank=True, max_length=64, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'password_reset_code',
            },
        ),
        migrations.AlterField(
            model_name='candidature_forum',
            name='date_inscri',
            field=models.DateField(default=datetime.date(2026, 6, 18), max_length=100),
        ),
    ]
