# Generated by Django 5.2.5 on 2026-06-22 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_passwordresetcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature_forum',
            name='date_inscri',
            field=models.DateField(default=datetime.date(2026, 6, 22), max_length=100),
        ),
    ]
